version: "3"
services:
  zookeeper:
    container_name: iris-zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: iris-kafka
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - ./server.properties:/bitnami/kafka/config/server.properties
      - ./producer.properties:/bitnami/kafka/config/producer.properties
    environment:
      - BITNAMI_DEBUG=true