clusters=A,B

A.bootstrap.servers=airflow-kafka:9092
A.security.protocol=SASL_PLAINTEXT
A.sasl.mechanism=PLAIN
A.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="root";

B.bootstrap.servers=kafka-b:9094
B.security.protocol=SASL_PLAINTEXT
B.sasl.mechanism=PLAIN
B.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="root";

A->B.enabled=true
A->B.topics=knowledge2-geo-test,heating-v2
replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy

# Connect internal topics must be RF=1 on single-broker clusters
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

# For mirrored topics created on B
replication.factor=1

# For MM2 offset syncs topic created on B
offset-syncs.topic.replication.factor=1

# Heartbeats/checkpoints topics too (safe for single broker)
heartbeats.topic.replication.factor=1
checkpoints.topic.replication.factor=1
