PREFIX building: <http://ies.data.gov.uk/ontology/ies-building1#>
PREFIX data: <http://ndtp.co.uk/data#>
PREFIX ies: <http://informationexchangestandard.org/ont/ies#>
PREFIX old_ies: <http://ies.data.gov.uk/ontology/ies4#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  
# Insert minimalist building mappings
INSERT {{
  GRAPH <http://ndtp.co.uk/detailed-building-geo-mapping> {{
    ?uprn data:hasFloorConstruction ?floorConstruction .
    ?uprn data:hasFloorInsulation ?floorInsulation .
  }}
}}
WHERE {{
  SELECT ?uprn ?floorConstruction ?floorInsulation
  WHERE {{
    ?uprn a building:UPRN ;
        ies:representationValue ?_uprn .

    ?structureUnit a building:StructureUnit ;
        ies:isIdentifiedBy ?uprn .
    ?structureUnitState a building:StructureUnitState ;
        ies:isStateOf ?structureUnit .
          
    ?_fc a ?floorConstruction ;
          ies:isPartOf ?structureUnitState .
    ?floorConstruction a building:FloorConstruction .

    ?_fi a ?floorInsulation ;
          ies:isPartOf ?structureUnitState .
    ?floorInsulation a building:FloorInsulation .
  }}
  LIMIT {LIMIT} 
  OFFSET {OFFSET} 
}}