PREFIX building: <http://ies.data.gov.uk/ontology/ies-building1#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX data: <http://ndtp.co.uk/data#>
PREFIX ies: <http://informationexchangestandard.org/ont/ies#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Create named graph for building-ward mapping
DROP SILENT GRAPH <http://ndtp.co.uk/building-ward-mapping> ;
CREATE GRAPH <http://ndtp.co.uk/building-ward-mapping> ;

# Insert building-to-ward mappings
INSERT {{
  GRAPH <http://ndtp.co.uk/building-ward-mapping> {{
    ?structureUnit data:locatedInWard ?ward .
    ?structureUnit data:inWardName ?wardName .
    ?uprn_id data:locatedInWardUPRN ?ward .
  }}
}}
WHERE {{
  ?ward a geo:Feature ;
        data:WD23NM ?wardName ;
        geo:asWKT ?wardWKT .

  ?uprn a building:UPRN .
  ?uprn ies:representationValue ?uprn_id .

  ?structureUnit ies:isIdentifiedBy ?uprn .
  ?structureUnit a building:StructureUnit .
  ?structureUnit ies:inLocation ?locationPoint .

  ?locationPoint ies:isRepresentedAs ?gp .
  ?gp a ies:ISO19125-WKT ;
      ies:representationValue ?point .

  FILTER(geof:sfIntersects(?point, ?wardWKT))
}}
